# GB0111

## Graph-Break Type
*Short name describing what triggered the graph break*
TypeError from user code

## Context
*Values or code snippet captured at the break point*
call_function({self.value}, {args}, {kwargs})

## Explanation
*Why this specific graph break happened*
msg

## Hints
*Suggestions for fixing or working around the break*
- Dynamo has detected that tracing the code will result in an error when running in eager. Please double check that your code doesn't contain a similar error when actually running eager/uncompiled.



[Back to Registry](../index.md)
