---
layout: default
---
# GB0188

## Graph-Break Type
*Short name describing what triggered the graph break*

getattr with no source

## Context
*Values or code snippet captured at the break point*

var_getattr {self} {name}

## Explanation
*Explanation of why the graph break was triggered*

Dynamo does not know how to access an attribute on an `nn.Module` instance that lacks a source. This is usually an internal error in Dynamo.

## Hints
*Hints on how to resolve the graph break*

- This is likely to be a Dynamo bug. Please report an issue to PyTorch.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/pytorch-labs/compile-graph-break-site/edit/main/docs/gb/gb0188.md)

[Back to Registry](../index.html)
