---
layout: default
---
# GB0242

## Graph-Break Type
*Short name describing what triggered the graph break*

Attempted to call op with non-contiguous `out=` tensor

## Context
*Values or code snippet captured at the break point*

self.value={self.value}, args={args}, kwargs={kwargs}

## Explanation
*Explanation of why the graph break was triggered*

Dynamo does not support this.

## Hints
*Hints on how to resolve the graph break*

- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->

[Back to Registry](../index.html)
