---
layout: default
---
# GB0262

## Graph-Break Type
*Short name describing what triggered the graph break*

unsupported contextlib.* API

## Context
*Values or code snippet captured at the break point*

{self.value}

## Explanation
*Explanation of why the graph break was triggered*

{self.value} not supported. This may be due to its use of context-specific operations that are not supported in Dynamo yet (i.e. Exception handling)

## Hints
*Hints on how to resolve the graph break*

- It may be possible to write Dynamo tracing rules for this code. Please report an issue to PyTorch if you encounter this graph break often and it is causing performance issues.


## Additional Information

<!-- ADDITIONAL INFORMATION START - Add custom information below this line -->

<!-- ADDITIONAL INFORMATION END -->


[Click here to add Additional Info](https://github.com/meta-pytorch/compile-graph-break-site/edit/main/docs/gb/gb0262.md)

[Back to Registry](../index.html)
