# GB0003

## Graph-Break Type
*Short name describing what triggered the graph break*
Attempt to trace generator

## Context
*Values or code snippet captured at the break point*
*No context provided.*

## Explanation
*Why this specific graph break happened*
Generators cannot be compiled directly with `torch.compile`.

## Hints
*Suggestions for fixing or working around the break*
- Call a generator from inside of a non-generator Python function and 
- compile that function instead.
- This graph break is fundamental - it is unlikely that Dynamo will ever be able to trace through your code. Consider finding a workaround.



[Back to Registry](../index.md)
